config/routes.rb
Rails.application.routes.draw do
  resources :articles
  get 'welcome/index'

  get 'test/new' => 'test#new'
  post 'test' => 'test#create'

  get 'articleType/:id/get_json' => 'article_type#get_json'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #controlador RESTFUL (rutas y acciones definidiadas)
  #except: [:delete]
  #only: [:delete]

  #es lo mismo qué
  	# get "/articles" 			index
  	# post "/articles" 			create
  	# delete "/articles:id"  destroy
  	# get "articles/:id" 		show
  	# get "/articles/new" 		new
  	# get "/articles/:id/edit" 	edit
  	# patch "/articles/:id" 	update
  	# put "/articles/:id"  		update

  	#Dirección de inicio del sistema
  	root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
	belongs_to :article_type

	validates :article_type, presence: true
	validates :name, presence:true, length: { minimum: 10}
end

app/models/article_type.rb
class ArticleType < ApplicationRecord
	has_many :articles
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/article_type_controller.rb
class ArticleTypeController < ApplicationController
	def get_json
		@article_type = ArticleType.find(params[:id])
		render json: @article_type
	end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :set_lst_article_types, only: [:new, :create, :edit]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
    #@lst_article_types = ArticleType.all
  end

  # GET /articles/1/edit
  def edit
    render layout: "modal_layout"
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        flash[:success] = "El Artículo fue creado exitosamente."
        format.html { redirect_to articles_path }
        format.json { render :index, status: :created, location: articles_path }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        flash[:success] = "El Artículo fue actualizado exitosamente."

# render js: "alert('Hello Rails');"
        format.html { render "articles/closemodal", layout: "modal_layout" }
        format.json { render :index, status: :ok, location: articles_path }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      flash[:success] = "El Artículo fue eliminado exitosamente."
      format.html { redirect_to articles_path }
      format.json { head :no_content }
    end
  end

  # def open_url
  #   @url = params[:url]
  # end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    def set_lst_article_types
      @lst_article_types = ArticleType.all
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:name, :date, :count, :article_type_id)
    end
end

app/controllers/test_controller.rb
class TestController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :set_lst_article_types, only: [:new, :create, :edit]
  
  def new
  	@article = Article.new
  end

  def create
  	@article = Article.new(article_params)

    respond_to do |format|
	    if @article.save
	        flash[:success] = "El Artículo fue creado exitosamente."
	        format.html { redirect_to articles_path }
	        format.json { render :index, status: :created, location: articles_path }
	    else
	        format.html { render :new }
	        format.json { render json: @article.errors, status: :unprocessable_entity }
	    end
	end
	end

	private
		def set_article
	      @article = Article.find(params[:id])
	    end

	    def set_lst_article_types
	      @lst_article_types = ArticleType.all
	    end

	    # Never trust parameters from the scary internet, only allow the white list through.
	    def article_params
	      params.require(:article).permit(:name, :date, :count, :article_type_id)
	    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/product_helper.rb
module ProductHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <ul>
      <% @article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <!-- Texto y campo a la derecha -->
<div class="row">
  <div class="form-group">  
    <%= f.label :name, class: "control-label col-md-1 col-sm-1 col-xs-12" %>
    <div class="col-md-4 col-sm-4 col-xs-12">
      <%= f.text_field :name, class:"form-control", autocomplete: "off" %>
    </div>
  </div>
</div>
<div class="row">
  <div class="form-group">
    <%= f.label :date, class: "control-label col-md-1 col-sm-1 col-xs-12" %>
    <div class="col-md-4 col-sm-4 col-xs-12">
      <%= f.text_field :date, 'data-provide' => 'datepicker', autocomplete: "off", class:"form-control", "data-date-format" => "dd/mm/yyyy", "data-date-autoclose" => "true", "data-date-language" => "es" %>
    </div>
  </div>
</div>

<!-- label con campo númerico a la derecha -->
<div class="row">
  <div class="form-group">  
    <%= f.label :count, class: "control-label col-md-1 col-sm-1 col-xs-12" %>
    <div class="col-md-4 col-sm-4 col-xs-12">
      <%= f.number_field :count, class:"form-control" %>
    </div>
  </div>
</div>


<!-- select("post", "person_id", Person.all.collect {|p| [ p.name, p.id ] }, {prompt: 'Select Person'}) -->

<div class="row">
  <div class="form-group">  
    <%= f.label :article_type_id, class: "control-label col-md-1 col-sm-1 col-xs-12" %>
    <div class="col-md-4 col-sm-4 col-xs-12">
    <%= f.select :article_type_id, @lst_article_types.collect {|p| ["#{p.code} - #{p.name}", p.id] }, {prompt: 'Seleccione'}, {class:"select2_single form-control"}  %>
    </div>
  </div>
</div>


  <div class="actions">
    <%= f.button "Cancelar", class: "btn btn-cancel", onclick: "hola();" %>
    <%= f.submit "Guardar", class: "btn btn-success" %>
  </div>
<% end %>

<script type="text/javascript">
  function hola ()
  {
    alert("holiwis");
  }
</script>

app/views/articles/closemodal.html.erb
<script type="text/javascript">
  $(document).ready(function() {
  	window.parent.closeModal();
  });
</script>

app/views/articles/edit.html.erb
<h1>Actualizar Artículo</h1>

<%= render 'form', article: @article %>

app/views/articles/index.html.erb
<h1>Artículos</h1>
<div class="add">
  <%= link_to new_article_path do%>
    <i class="fa fa-plus-square theme-color"></i> Agregar Artículo
  <%end%>
</div>
<table class="dataTable stripe hover order-column row-border">
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
      <th>Name</th>
      <th>Date</th>
      <th>Count</th>
      <th>Tipo</th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td class="align-center">
          <%= button_tag "", type: "button", class:"modalButton button-nostyle", title: "Detalle", data: { toggle: "modal",src: article_path(article), width: "80%", height: "70%", target: "#myModal"} do%>
            <i class="fa fa-search-plus theme-color"></i>
          <%end%>
        </td>
        <td class="align-center">
        <%= button_tag "", type: "button", class:"modalButton button-nostyle", title: "Detalle", data: { toggle: "modal",src: edit_article_path(article), width: "350", height: "800", target: "#myModal"} do%>
            <i class="fa fa-edit green"></i>
          <%end%>
        </td>
        <td class="align-center">
          <%= link_to article, 'data-toggle' => "tooltip", title: "Eliminar", method: :delete, data: { confirm: "¿Desea eliminar el artículo: <b>#{article.name}</b>?" } do%>
              <i class="fa fa-remove red"></i>
          <%end%>
        </td>
        <td><%= article.name %></td>
        <td><%= article.date %></td>
        <td><%= article.count %></td>
        <td><%= article.article_type.name %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/articles/new.html.erb
<h1>Nuevo Artículo</h1>

<%= render 'form', article: @article %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @article.name %>
</p>

<p>
  <strong>Date:</strong>
  <%= @article.date %>
</p>

<p>
  <strong>Count:</strong>
  <%= @article.count %>
</p>

<p>
  <strong>Article Type:</strong>
  <%= @article.article_type.name %>
</p>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

		<title>proyecto_base</title>
    <%= favicon_link_tag 'favicon.ico'%>
    <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
		<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
		<%= csrf_meta_tags %>

	</head>
	<body class="nav-md">
    <div class="container body">
      <div class="main_container">
        <div class="col-md-3 left_col menu_fixed">
          <div class="left_col scroll-view">
            <div class="navbar nav_title" style="border: 0;">
              <a href="index.html" class="site_title"><i class="fa fa-file-code-o"></i><span>SOISOFT</span></a>
            </div>
            <div class="clearfix"></div>
            <br />
            <!-- sidebar menu -->
            <%= render "partials/sidebar_menu" %>
            <!-- /sidebar menu -->

          </div>
        </div>

        <!-- top navigation -->
        <%= render "partials/top_navigation" %>
        <!-- /top navigation -->


        <!-- page content -->
        <div class="right_col" role="main">
          <div class="">
            
            <% if flash[:alert]%>
              <p class="alert"><%= alert %></p>
            <%end%>

            <%= yield %>
          </div>
        </div>
        <!-- /page content -->

        <!-- footer content -->
        <footer id="footerapp">
          <div class="pull-right">
            SOISOFTBase - Proyecto base para proyectos en ruby by SOISOFT
          </div>
          <div class="clearfix"></div>
          <%= render "partials/modal" %>
        </footer>
        <!-- /footer content -->
      </div>
    </div>

    <script type="text/javascript">
      var CURRENT_URL = window.location.href.split('?')[0],
      $BODY = $('body'),
      $MENU_TOGGLE = $('#menu_toggle'),
      $SIDEBAR_MENU = $('#sidebar-menu'),
      $SIDEBAR_FOOTER = $('.sidebar-footer'),
      $LEFT_COL = $('.left_col'),
      $RIGHT_COL = $('.right_col'),
      $NAV_MENU = $('.nav_menu'),
      $FOOTER = $('#footerapp');

      $(document).ready(function() {
        $(".select2_single").select2({
          placeholder: "Seleccionar",
          allowClear: true,
          width: '100%'
        });
        $(".select2_group").select2({});
        $(".select2_multiple").select2({
          maximumSelectionLength: 4,
          placeholder: "Seleccionar máximo 4 elementos",
          allowClear: true
        });

        $('.dataTable').DataTable({
            //Configuraciones Exportación
            "dom": '<"export-title"><"clear">T<"clear">lfrtip',
            "tableTools": {
                "sSwfPath": "/assets/dataTables/extras/swf/copy_csv_xls_pdf.swf",
                "aButtons": [ {"sExtends": "xls", "sButtonText": ""}, 
                              {"sExtends": "pdf", "sButtonText": ""} ]
            },

            //Configuraciones lenguaje
            "oLanguage": {
              "sInfo": "Mostrando del <b>_START_</b> al <b>_END_</b> de <b>_TOTAL_</b> registros",
              "sEmptyTable": "No hay datos disponibles",
              "sLengthMenu": 'Mostrar <select>'+
                              '<option value="10">10</option>'+
                              '<option value="20">20</option>'+
                              '<option value="30">30</option>'+
                              '<option value="40">40</option>'+
                              '<option value="50">50</option>'+
                              '<option value="-1">Todos</option>'+
                              '</select> registros',
              "sLoadingRecords": "Por favor espere - cargando...",
              "sSearch": "<i class='fa fa-search'></i> Buscar:",
              "sInfoEmpty": "No hay registros para mostrar",
              "sInfoFiltered": "(filtrados de _MAX_ registros totales)",
              "sZeroRecords": "No se encontraron registros",
              "oPaginate": {
                "sNext": "Siguiente",
                "sPrevious": "Anterior"
                }
            },
            
            }
          );

        $('[data-toggle="tooltip"]').tooltip(); 

        //initialize modal
        iframeModalOpen();

        //JS notifymsg.js
        //Aviso de Exito
        if ('<%= flash[:success]%>' != ''){
         display_message('¡Éxito!','<%= flash[:success]%>', 'success');
        }

        //Aviso de Error
        if ('<%= flash[:error]%>' != ''){
          display_message('Error','<%= flash[:error]%>', 'error');
        }

        //Aviso de información
        if ('<%= flash[:notice]%>' != ''){
          display_message('Aviso','<%= flash[:notice]%>', 'info');
        }

        //Aviso Confirmación

        //Override the default confirm dialog by rails
        display_confirm();

        window.closeModal = function(){
          $('#myModal').modal('toggle');
        };

      });

    </script>
  </body>
</html>

app/views/layouts/modal_layout.html.erb
<!DOCTYPE html>
<html>
	<head>
	    <meta charset="utf-8">
	    <meta http-equiv="X-UA-Compatible" content="IE=edge">
	    <meta name="viewport" content="width=device-width, initial-scale=1">

		<title>proyecto_base</title>
	    <%= favicon_link_tag 'favicon.ico'%>
	    <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
		<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
	    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
		<%= csrf_meta_tags %>
	</head>
	<body class="nav-md">
    	<div class="container body">
      		<div class="main_container">
			<!-- page content -->
		        <div class="right_col" role="main">
		          <div class="">
		            
		            <% if flash[:alert]%>
		              <p class="alert"><%= alert %></p>
		            <%end%>

		            <%= yield %>
		          </div>
		        </div>
        	<!-- /page content -->
        	</div>
    	</div>
    	<script type="text/javascript">
      var CURRENT_URL = window.location.href.split('?')[0],
      $BODY = $('body'),
      $MENU_TOGGLE = $('#menu_toggle'),
      $SIDEBAR_MENU = $('#sidebar-menu'),
      $SIDEBAR_FOOTER = $('.sidebar-footer'),
      $LEFT_COL = $('.left_col'),
      $RIGHT_COL = $('.right_col'),
      $NAV_MENU = $('.nav_menu'),
      $FOOTER = $('#footerapp');

      $(document).ready(function() {
        $(".select2_single").select2({
          placeholder: "Seleccionar",
          allowClear: true,
          width: '100%'
        });
        $(".select2_group").select2({});
        $(".select2_multiple").select2({
          maximumSelectionLength: 4,
          placeholder: "Seleccionar máximo 4 elementos",
          allowClear: true
        });

        $('.dataTable').DataTable({
            //Configuraciones Exportación
            "dom": '<"export-title"><"clear">T<"clear">lfrtip',
            "tableTools": {
                "sSwfPath": "/assets/dataTables/extras/swf/copy_csv_xls_pdf.swf",
                "aButtons": [ {"sExtends": "xls", "sButtonText": ""}, 
                              {"sExtends": "pdf", "sButtonText": ""} ]
            },

            //Configuraciones lenguaje
            "oLanguage": {
              "sInfo": "Mostrando del <b>_START_</b> al <b>_END_</b> de <b>_TOTAL_</b> registros",
              "sEmptyTable": "No hay datos disponibles",
              "sLengthMenu": 'Mostrar <select>'+
                              '<option value="10">10</option>'+
                              '<option value="20">20</option>'+
                              '<option value="30">30</option>'+
                              '<option value="40">40</option>'+
                              '<option value="50">50</option>'+
                              '<option value="-1">Todos</option>'+
                              '</select> registros',
              "sLoadingRecords": "Por favor espere - cargando...",
              "sSearch": "<i class='fa fa-search'></i> Buscar:",
              "sInfoEmpty": "No hay registros para mostrar",
              "sInfoFiltered": "(filtrados de _MAX_ registros totales)",
              "sZeroRecords": "No se encontraron registros",
              "oPaginate": {
                "sNext": "Siguiente",
                "sPrevious": "Anterior"
                }
            },
            
            }
          );

        $('[data-toggle="tooltip"]').tooltip(); 

        //initialize modal
        iframeModalOpen();

        //JS notifymsg.js
        //Aviso de Exito
        if ('<%= flash[:success]%>' != ''){
         display_message('¡Éxito!','<%= flash[:success]%>', 'success');
        }

        //Aviso de Error
        if ('<%= flash[:error]%>' != ''){
          display_message('Error','<%= flash[:error]%>', 'error');
        }

        //Aviso de información
        if ('<%= flash[:notice]%>' != ''){
          display_message('Aviso','<%= flash[:notice]%>', 'info');
        }

        //Aviso Confirmación

        //Override the default confirm dialog by rails
        display_confirm();

      });

    </script>
    </body>
</html>

app/views/partials/_modal.html.erb
<div class="modal fade" id="myModal">
	<div class="modal-dialog">
		<div class="modal-content">

			<div class="modal-body">
      
		      <div class="close-button">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
		      </div>
		      <div class="border embed-responsive embed-responsive-16by9">
				<iframe class="embed-responsive-item" frameborder="0"></iframe>
		      </div>
			</div>

		</div><!-- /.modal-content -->
	</div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/partials/_sidebar_menu.html.erb
<!-- sidebar menu -->
<div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
  <div class="menu_section">
    <h3>Menú</h3>
    <ul class="nav side-menu">
    <li>
      <%= link_to root_path do %>
        <i class="fa fa-home"></i>Home
      <%end%>
    </li>
    <li>
      <%= link_to "/articles" do %>
        <i class="fa fa-file-code-o"></i>Articulos
      <%end%>
    </li>
    <li>
      <%= link_to "/test/new" do %>
        <i class="fa fa-file-code-o"></i>Articulos TEST
      <%end%>
    </li>
      <li><a><i class="fa fa-area-chart"></i> Reportes <span class="fa fa-chevron-down"></span></a>
        <ul class="nav child_menu">
          <li><a href="index.html">Dashboard</a></li>
          <li><a href="index2.html">Dashboard2</a></li>
          <li><a href="index3.html">Dashboard3</a></li>
        </ul>
      </li>
      <li><a><i class="fa fa-sitemap"></i> Multilevel Menu <span class="fa fa-chevron-down"></span></a>
        <ul class="nav child_menu">
            <li><a href="#level1_1">Level One</a>
            <li><a>Level One<span class="fa fa-chevron-down"></span></a>
              <ul class="nav child_menu">
                <li class="sub_menu"><a href="level2.html">Level Two</a>
                </li>
                <li><a href="#level2_1">Level Two</a>
                </li>
                <li><a href="#level2_2">Level Two</a>
                </li>
              </ul>
            </li>
            <li><a href="#level1_2">Level One</a>
            </li>
        </ul>
      </li>  
    </ul>
  </div>
  <div class="menu_section">
    <h3>Live On</h3>
    <ul class="nav side-menu">
      <li><a><i class="fa fa-bug"></i> Additional Pages <span class="fa fa-chevron-down"></span></a>
        <ul class="nav child_menu">
          <li><a href="e_commerce.html">E-commerce</a></li>
          <li><a href="projects.html">Projects</a></li>
          <li><a href="project_detail.html">Project Detail</a></li>
          <li><a href="contacts.html">Contacts</a></li>
          <li><a href="profile.html">Profile</a></li>
        </ul>
      </li>
      <li><a><i class="fa fa-windows"></i> Extras <span class="fa fa-chevron-down"></span></a>
        <ul class="nav child_menu">
          <li><a href="page_403.html">403 Error</a></li>
          <li><a href="page_404.html">404 Error</a></li>
          <li><a href="page_500.html">500 Error</a></li>
          <li><a href="plain_page.html">Plain Page</a></li>
          <li><a href="login.html">Login Page</a></li>
          <li><a href="pricing_tables.html">Pricing Tables</a></li>
        </ul>
      </li>
      <li><a><i class="fa fa-sitemap"></i> Multilevel Menu <span class="fa fa-chevron-down"></span></a>
        <ul class="nav child_menu">
            <li><a href="#level1_1">Level One</a>
            <li><a>Level One<span class="fa fa-chevron-down"></span></a>
              <ul class="nav child_menu">
                <li class="sub_menu"><a href="level2.html">Level Two</a>
                </li>
                <li><a href="#level2_1">Level Two</a>
                </li>
                <li><a href="#level2_2">Level Two</a>
                </li>
              </ul>
            </li>
            <li><a href="#level1_2">Level One</a>
            </li>
        </ul>
      </li>                  
      <li><a href="javascript:void(0)"><i class="fa fa-laptop"></i> Landing Page <span class="label label-success pull-right">Coming Soon</span></a></li>
    </ul>
  </div>

</div>
<!-- /sidebar menu -->

app/views/partials/_top_navigation.html.erb
<!-- top navigation -->
<div class="top_nav">
  <div class="nav_menu">
    <nav>
      <div class="nav toggle">
        <a id="menu_toggle"><i class="fa fa-bars"></i></a>
      </div>

      <ul class="nav navbar-nav navbar-right">
        <li class="">
          <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
          <%= image_tag("img.jpg", :alt => "") %>John Doe
            <span class=" fa fa-angle-down"></span>
          </a>
          <ul class="dropdown-menu dropdown-usermenu pull-right">
            <li><a href="javascript:;"> Profile</a></li>
            <li>
              <a href="javascript:;">
                <span class="badge bg-red pull-right">50%</span>
                <span>Settings</span>
              </a>
            </li>
            <li><a href="javascript:;">Help</a></li>
            <li><a href="login.html"><i class="fa fa-sign-out pull-right"></i> Log Out</a></li>
          </ul>
        </li>
      </ul>
    </nav>
  </div>
</div>
<!-- /top navigation -->

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>



<button type="button" class="modalButton" data-toggle="modal" data-src="https://www.youtube.com/embed/mWRsgZuwf_8" data-width="640" data-height="360" data-target="#myModal" data-video-fullscreen="">Youtube</button>